if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="amc12-2026-04-24-student-1";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(200);
defaultpen(0.9);
real r = 5/dir(54).x, h = 5 tan(54*pi/180);
pair A = (5,0), B = A+10*dir(72), C = (0,r+h), E = (-5,0), D = E+10*dir(108);
draw(A--B--C--D--E--cycle);
label("\(A\)",A+(0,-0.5),SSE);
label("\(B\)",B+(0.5,0),ENE);
label("\(C\)",C+(0,0.5),N);
label("\(D\)",D+(-0.5,0),WNW);
label("\(E\)",E+(0,-0.5),SW);
real l = 5*sqrt(3);
pair ab = (h+l)*dir(72), bc = (h+l)*dir(54);
pair AB = (ab.y, h-ab.x), BC = (bc.x,h+bc.y), CD = (-bc.x,h+bc.y), DE = (-ab.y, h-ab.x), EA = (0,-l);
draw(A--AB--B^^B--BC--C^^C--CD--D^^D--DE--E^^E--EA--A, dashed);
// dot(A);
dot(B);
dot(C);
dot(D);
dot(E);
dot(AB);
dot(BC);
dot(CD);
dot(DE);
dot(EA);
